container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        token: circleci-agent-token@azurekeyvault
        metadata:
          annotations:
            azure-keyvault-env-inject: "true"