container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
  spec:
    securityContext:
      runAsNonRoot: true
      podAnnotations:
        azure-key-vault-to-kubernetes/inject: "true"
        azure-key-vault-to-kubernetes/secret-name: circelci-agent-token
