container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        token: circleci-container-agent@azurekeyvault
        # spec:
        #   securityContext:
        #     runAsNonRoot: true