container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        token: circleci-agent-token@azurekeyvault
        metadata:
          annotations:
            azure-key-vault-env-injection: enabled