container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
    customSecret: circleci-container-agent
    environmentVariables:
      CIRCLECI_AGENT_TOKEN: circleci-agent-token@azurekeyvault