container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        spec:
          securityContext:
            runAsNonRoot: true
    customSecret: circleci-agent-container@azurekeyvault