container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        token: CIRCLECI_RUNNER_TOKEN
    environment:
      CIRCLECI_RUNNER_TOKEN: circleci-agent-token@azurekeyvault
      KUBE_TOKEN_SECRETS: CIRCLECI_RUNNER_TOKEN