container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        metadata:
          annotations:
            azure-key-vault-to-kubernetes/inject: "true"
            azure-key-vault-to-kubernetes/secret-name: circelci-agent-token
  spec:
    securityContext:
      runAsNonRoot: true
