container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
    environment:
      - CIRCLECI_AGENT_TOKEN: circleci-agent-token@azurekeyvault
      - KUBE_TOKEN_SECRETS: "liquorichris.class: CIRCLECI_AGENT_TOKEN"