container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        spec:
          securityContext:
            runAsNonRoot: true
    # customSecret: circleci-container-agent@azurekeyvault
    environment:
      KUBE_TOKEN_SECRETS: circleci-container-agent@azurekeyvault