container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
  spec:
    securityContext:
      runAsNonRoot: true
      podAnnotations:
        metadata:
          azure-key-vault-to-kubernetes/inject: "true"
          azure-key-vault-to-kubernetes/secret-name: circelci-agent-token
