container-agent:
  agent:
    azure.workload.identity/use: "true"
    forceUpdate: true
    resourceClasses:
      liquorichris/container-agent:
        spec:
          securityContext:
            runAsNonRoot: true
    customSecret: circleci-agent-token
