container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        token: circleci-agent-token@azurekeyvault
    environment:
      KUBE_TOKEN_SECRETS: circleci-agent-token@azurekeyvault