container-agent:
  agent:
    resourceClasses:
      metadata:
        annotations:
          azure-keyvault-env-inject: "true"
      liquorichris/class:
        token: circleci-agent-token@azurekeyvault