container-agent:
  agent:
    resourceClasses:
      liquorichris/class:
        token: circleci-agent-token@azurekeyvault
    environmentVariables:
      liquorichris.class: circleci-agent-token@azurekeyvault
