configMapGenerator:
- name: job-inputs
  behavior: merge
  literals:
  - taskpods: |
    resourceClasses:
    {{- range $rc, $value := .Values.agent.resourceClasses }}
        {{- $rc | replace "/" "." | nindent 6 }}:
        {{- range $key, $value := $value }}
        {{- if ne $key "token" }}
          {{- $key | nindent 8 }}:
            {{- toYaml $value | nindent 10 }}
        {{- end }}
        {{- end }}
    {{- end }}
