apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: job-inputs
  behavior: merge
  literals:
  - taskpods: |
    resourceClasses:
      liquorichris.container-agent:
        token: KUBE_KEYVAULT_SECRET
