apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
name: circleci-container-agent
namespace: circleci
configMapGenerator:
- name: 
  behavior: merge
  literals:
    - taskpods: |
      resourceClasses:
        liquorichris.container-agent:
          token: KUBE_KEYVAULT_SECRET
